### ISSUE TITLE
Support for default roles

### ISSUE THREAD

**Issue by ankon** [uswitch/kiam#1]
kube2iam supports assigning a default role to a pod that doesn't specify another role explicitly. From what I can see kiam is not able to do this.

My use case: I try to keep configuration down to a minimum, and rely a lot on default values. For that reason many of my pods that need no special permissions do not specify a role, and instead assume the environment will be setup nicely.

**Comment by pingles** [comment]
Yep- it definitely doesn't do this currently. Happy for it to be added- I'll see if I can get a chance to do it soon but if not a PR would also be welcome.

**Comment by pingles** [comment]
For now I'm going to close this- I'm happy sticking to requiring Pods to explicitly annotate roles for now. Open to discussing again in the future.
