### ISSUE TITLE
Deployment with Istio

### ISSUE THREAD

**Issue by pingles** [uswitch/kiam#13]
Instead of using the gRPC library for load-balancing it would be interesting to see how well/easy Kiam works within an Istio mesh.

Testing how easy it is to support Istio's distributed tracing would be cool- I guess most of this work would probably exist within client libraries rather than kiam itself.

**Comment by srizzling** [comment]
@pingles What happened with your investigation here?

**Comment by kgoralski** [comment]
@pingles so kiam and istio can coexist, right ?
or istio is doing similar things to kiam too ?

**Comment by pingles** [comment]
We never got around to testing it I'm afraid.

**Comment by kgoralski** [comment]
just fyi, installed kiam first and  downloaded the istio 1.0.0 and installed it like this: 
```
helm upgrade --recreate-pods --namespace istio-system --set grafana.enabled=true \
             --set global.configValidation=false \
             --set sidecarInjectorWebhook.enabled=false \
             istio \
             install/kubernetes/helm/istio
```
it seems that it works but actually I don't know how traffic is forwarded now :D
