### ISSUE TITLE
Assumed role arn not trusted by instance role

### ISSUE THREAD

**Issue by kevtaylor** [uswitch/kiam#135]
Kiam version 2.7

When a role is created as an 'override' to the generated version in kube-aws, there are assume errors as:

```
{"level":"error","msg":"error requesting credentials: AccessDenied: User: arn:aws:sts::034324643013:assumed-role/us-west-2-md-Controller/i-084d38eaacc983616 is not authorized to perform: sts:AssumeRole on resource: arn:aws:iam::034324643013:role/us-west-2-md-Kiam\n\tstatus code: 403, request id: 01b4ba14-9af0-11e8-b9ba-c1a73e9c177a","pod.iam.role":"us-west-2-md-external-dns","time":"2018-08-08T09:47:04Z"}
```
In this example the `us-west-2-md-Controller` is the one that is created by kube-aws when the cluster spins (we specify this role name in the cluster.yaml configs)

And we want to replace the kiam server with `- --assume-role-arn=arn:aws:iam::034324643013:role/us-west-2-md-Kiam`

**Comment by pingles** [comment]
Ah... I've just reread the error- it looks like your instance `i-084d38eaacc983616` is attempting to assume `arn:aws:iam::034324643013:role/us-west-2-md-Kiam` and isn't being permitted- does your `us-west-2-md-Kiam` role have sufficient assume role policy to permit it? 

I initially thought it was Kiam not attempting to assume the role you'd specified in `--assume-role-arn` but it looks like it might be a trust policy issue?

**Comment by kevtaylor** [comment]
So, if I add an AssumeRole to the controller iam ie:
```
{
      "Sid": "",
      "Effect": "Allow",
      "Principal": {
        "AWS": "arn:aws:iam::034324643013:role/us-west-2-md-Controller"
      },
      "Action": "sts:AssumeRole"
    }
```

That works, but that sort of defeats the object because I want to create the roles independently of the cluster. Is there a more 'generic' way?

**Comment by tombooth** [comment]
Can you expand on what you mean by 'creating roles independently of the cluster' and a 'more generic way'?

At the moment the Kiam has to use AWS roles as a way of allowing operators to restrict only certain roles to be available to the Kubernetes cluster. It assumes this 'cluster identity' role on start and as specified by `--assume-role-arn`. This is very corse and relies on Kiam restricting the which pods can ask for which roles, through use of namespace restrictions. 

By default, it will use the instance profile to assume the Kiam role specified using `--assume-role-arn`. This can be done using any other AWS credentials provider in the default chain of the Go SDK (env vars for example).

We plan on passing some information about the Kubernetes resource requesting the role through in the role session name, so that people can make assume policy slightly more restrictive than all of the cluster.

There is a proposal from AWS to help expose Kubernetes as an OpenID Connect Provider. This can then be used in assume policy to refer to Kubernetes identies in the assume policy, rather than our AWS proxy identity.

**Comment by kevtaylor** [comment]
At present we use kube-aws to generate an IAM controller instance role 
We then create IAM roles for our pods and use the IAM controller role as a trust
We want to create our own IAM role to mimic the controller one - ie. Be under our control rather than use the kube-aws one
We then want to assign that role as the trust to our pods rather than the instance controller role

So we thought that by adding the `-assume-role-arn` flag and repointing the kiam-server to our own one would work

**Comment by kevtaylor** [comment]
Because the kube-aws one is only created at cluster provision time, this makes it dynamic and I want to allow the newly generated role to have full control. The error message suggests that we need to add the controller as a trust to the new role - this is a chicken and egg situation as we don't want either to know about each other

**Comment by pingles** [comment]
@kevtaylor yeah that sounds right. The error at the top sounded like it was a problem that the role your Kiam server assumes (specified by `assume-role-arn`) didn't have the trust policy to allow the instance running the server to assume it. So your server role just needs the trust policy to permit the EC2 instances running the server to assume the role.

I think you'd need something that would bind the `assume-role-arn` to your cluster always though. You _could_ bypass by creating some long-lived credentials and setting the usual env vars to pass the access and secret key to the server, but that would also allow anyone with that secret to assume any role in your cluster so it's probably better to stick with using the instance-based credentials?

**Comment by pingles** [comment]
So, from what you've described, I think you could accomplish:

1. Create a role for the Kiam server, this role is passed via `assume-role-arn`. For example, `mycluster-kiam-server`.
2. You add trust policy for `mycluster-kiam-server` to allow the subset of nodes that run the server to call `sts:AssumeRole` for that role.
3. Any IAM roles you give to your pods then need trust policy to permit `mycluster-kiam-server` to assume them.

**Comment by pingles** [comment]
Did I get that right @uswitch/cloud?

**Comment by kevtaylor** [comment]
@pingles Thanks but it is point 2). That stumps me here. How do I know what that subset is, if I haven't created the nodes yet? - the `mycluster-kiam-server` role would be created prior to the cluster spinning, so I need a way of trusting anything that 'may be' in the node range. ie Some sort of wildcard, but it looks to me like trust policies have to have the specific arn in them

**Comment by pingles** [comment]
Ah! Yeah we assign roles to the instances also- so there's a role for regular nodes in our clusters (that can access some cluster assets on S3) and a separate role for the nodes running Kiam server etc.

**Comment by kevtaylor** [comment]
I can see now how you work this and need to go back for a rethink. Thanks for your quick responses

**Comment by pingles** [comment]
It'd be great to get your feedback on this ahead of us writing something up- #8 has been around forever and having something to document how to configure IAM for your cluster would be useful.

**Comment by kevtaylor** [comment]
@pingles Basically what we would need to do is create the role up front and then get kube-aws to attach the cluster policies to it (effectively disable the controller role from the cloud formation and create it outside). Then we can use our own role as the trust for kiam and create it (and any other pod roles) in advance. Our intention is to set a flag like selfManaged: true and then supply kube-aws a role of our choice. (This is the theory anyway - we're going to explore this shortly)

**Comment by pingles** [comment]
Ah... so it's because CloudFormation is autogenerating some of the role names?

Does CloudFormation let you reference roles- could you define the server role (with a name you hard-code) and have it trust the autogenerated role names associated for the controller?

**Comment by kevtaylor** [comment]
Yes - you can specify a role name like kt-Controller but.. it prepends <region> to the front.
In the latest kube it prepends <cluster>-<region> and this is going to bust all our roles because we using the former version. This is why we are looking at managing this ourselves.
If you don't specify a named role it will autogenerate one for you
