### ISSUE TITLE
failed dns SRV record lookup due to lookup _grpclb._tcp.kiam-server

### ISSUE THREAD

**Issue by y-batsianouski** [uswitch/kiam#144]
Hello!

With `GRPC_GO_LOG_SEVERITY_LEVEL=info` and `GRPC_GO_LOG_VERBOSITY_LEVEL=8` 

we have `INFO: grpc: failed dns SRV record lookup due to lookup _grpclb._tcp.kiam-server on 100.64.0.10:53: no such host.`  almost each second in logs.

Kubernetes cluster is bootstrapped with kops

Is it ok?

**Comment by roffe** [comment]
Change the service port name from `grpc` to `grpclb` in your Kiam deployment

https://github.com/uswitch/kiam/blob/master/deploy/server.yaml#L91

**Comment by 2rs2ts** [comment]
We are having this same problem but the suggested resolution did not fix it. We are running k8s 1.12.2 and kiam 2.7. This was fine on k8s 1.11.2 but upgrading to 1.12.2 introduced this problem.

**Comment by 2rs2ts** [comment]
Heh, turns out it was a typo (not my typo though) ;)
