### ISSUE TITLE
error processing request: unexpected error: context canceled

### ISSUE THREAD

**Issue by y-batsianouski** [uswitch/kiam#145]
Time to time we have error:
agent: 
```json
{"addr":"100.96.18.27:34478","level":"error","method":"GET","msg":"error processing request: unexpected error: context canceled","path":"/latest/meta-data/iam/security-credentials/IAMTest","status":500,"time":"2018-08-22T07:53:33Z"}
```
server: 
```json
{"level":"error","msg":"error requesting credentials: RequestCanceled: request context canceled\ncaused by: context canceled","pod.iam.role":"IAMTest","time":"2018-08-22T07:53:33Z"}
{"level":"error","msg":"error requesting credentials: context canceled","pod.iam.role":"IAMTest","time":"2018-08-22T07:53:33Z"}
```

also sometimes we have next logs for agent:
```json
{"addr":"100.96.18.30:48196","level":"error","method":"GET","msg":"error processing request: error checking assume role permissions: rpc error: code = Canceled desc = context canceled","path":"/latest/meta-data/iam/security-credentials/InfraKube2IamTest","status":500,"time":"2018-08-22T09:13:49Z"}
```

There are no additional messages with  `GRPC_GO_LOG_SEVERITY_LEVEL=info` and `GRPC_GO_LOG_VERBOSITY_LEVEL=8`

And there is two log variants from `aws cli`:
```
aws s3api list-buckets
'access_key'
```
```
aws s3api list-buckets
Unable to locate credentials. You can configure credentials by running "aws configure".
```

Kubernetes cluster bottstrapped with kops.

Thanks!

**Comment by pingles** [comment]
Context cancelled errors mean that the `context.Context` was cancelled during some long-running operation.

If you see the messages in the agent then it's possible that the client is disconnecting before the agent is able to serve responses. In which case, I'd check whether there's connectivity issues between the server and agent.

I'd change the log level on the server and agent to debug to see what they're attempting to perform before the context is cancelled.

**Comment by roffe** [comment]
I'm wondering if this might be the default IPVS timeout of 900 sec we are seeing. 

https://github.com/cloudnativelabs/kube-router/issues/521

I'm wondering if kube-proxy might have the same phenomen. 

@y-batsianouski Do you have a period of long idle before the sporadic errors come?

**Comment by y-batsianouski** [comment]
Fixed by set larger timeouts.

Thank you!

**Comment by jordiclariana** [comment]
Hey @y-batsianouski , I'm experiencing very same problem as you did. Can you please elaborate on your solution (larger timeouts), please?
Thanks!

**Comment by kuzaxak** [comment]
@jordiclariana 

```
      envVar(key: 'AWS_METADATA_SERVICE_TIMEOUT', value: '5'),
      envVar(key: 'AWS_METADATA_SERVICE_NUM_ATTEMPTS', value: '5')
```
