### ISSUE TITLE
Server error: aws metadata api not available

### ISSUE THREAD

**Issue by philwinder** [uswitch/kiam#155]
Hi, 
I'm trying to install on AWS EKS.

I've almost got kiam working using the `v2.8` tag, but the server is failing with:
```
{"level":"info","msg":"starting server","time":"2018-09-12T15:32:18Z"}
{"level":"info","msg":"detecting arn prefix","time":"2018-09-12T15:32:18Z"}
{"level":"fatal","msg":"error creating listener: error detecting arn prefix: aws metadata api not available","time":"2018-09-12T15:32:18Z"}
```

I've tested this manually, and I can confirm that the pod cannot ping or wget `169.254.169.254`. No pod can. However, I can connect to any external address (e.g. google, amazon, etc.)

I also tried to use the `--role-base-arn` flag, but the code still seems to try and connect to the metadata service.

I know this is not quite within kiam's remit, but I couldn't find any info w.r.t. eks + metadata. Do you know why my pod can't access this internal address?

Thanks in advance.

Phil

**Comment by jkaflik** [comment]
I've got same issue. It seems iptables rule is also affecting kiam server.
Had to reboot nodes with kiam agent disabled to restore original routing to `169.254.169.254`.
not sure if `--iptables --host-interface=!eth0` is enough configured

**Comment by willtrking** [comment]
Just ran into this myself.

My fix was preventing the server pods and agent pods from running on the same machine. My assumption is that this fixes it as the server pods were having their metadata API traffic intercepted by the iptable rules from the agent pods, but I could be way way off there.

If we look closely at the example deployment scripts, we can see that the server pods are using a `nodeSelector` to run on masters, and the agents have one to only run on the nodes. With EKS it's of course impossible to run on the masters, so I used node taint's to prevent the agent from running on the same node as the server.

Hope this helps.

**Comment by philwinder** [comment]
For me it appears the problem was slightly different. My nodes are in a private subnet. I have to run BOTH agent and server pods in `hostNetwork: true` mode. I saw hints of this everywhere, but there is no documentation clearly stating it.

**Comment by kgoralski** [comment]
is this one related? https://github.com/uswitch/kiam/issues/151
any news? :)

**Comment by pingles** [comment]
I don't think this issue is related to #151 I'm afraid. As noted above, Kiam was built with the expectation to enhance security through having agents (running on nodes running user workloads) have no IAM permissions to `sts:AssumeRole` and that servers (running on nodes that run no user workloads) are the only ones that can access the metadata api/AWS APIs with the necessary permissions.

I'm going to close this issue for now as I don't think its related to the others.

**Comment by kgoralski** [comment]
@pingles I think above problem is because `--role-base-arn-autodetect` didn't work.

**Comment by dnascimento** [comment]
We needed to use `hostNetwork: true`
