### ISSUE TITLE
Autodiscover base ARN

### ISSUE THREAD

**Issue by slok** [uswitch/kiam#16]
Hi! 

We want to migrate from Kube2IAM to Kiam, but had to stop it because Kiam lacks the autodiscover base ARN feature: [the autodiscover of base ARN](https://github.com/jtblin/kube2iam#base-arn-auto-discovery)

Is this feature planned in Kiam?

Thank you!

**Comment by pingles** [comment]
Hi,

We've not talked about adding it yet- at least in our deployments we've been happy to specify the base arn as part of the deployment.

I'm not against adding it but not sure how quickly we'd support it.

**Comment by pingles** [comment]
Just a few notes in case I come back to this today/later.

I've added a little more behaviour into the credentials cache to resolve the ARN for a role- allowing it to handle either just roles, or arns.

It's probably worth extracting this stuff into something like an `ARNResolver` interface- which could then also have some smarts to figure out what prefix it should already use.

**Comment by pingles** [comment]
So I picked up the refactoring and added the same autodiscover arn from kube2iam (thanks again for their work- I've included their BSD license in the source file).

The code is currently in the branch https://github.com/uswitch/kiam/tree/autodetect-arn and branch's image is also available `quay.io/uswitch/kiam:autodetect-arn`.

@slok do you want to give it a run and check that's sufficient. It'd be good to know why autodetection was critical- it definitely makes it easier to run but be good to understand more about your needs.

**Comment by pingles** [comment]
I've tagged a release: it's in the `quay.io/uswitch/kiam:v2.4` image.
