### ISSUE TITLE
Assume role from a different AWS account

### ISSUE THREAD

**Issue by sagivegh** [uswitch/kiam#166]
It will be great if you can add parameter in the role annotation, for allowing cross-account role assume.

**Comment by dng-dev** [comment]
have you tried it? Can u give more details whats the exact use case ?

**Comment by pingles** [comment]
You can specify a full qualified ARN for the role already. For example:

```
  iam.amazonaws.com/role: arn:xxxxxxx
```

That'll let you obtain credentials cross-account (assuming your server is configured with a role that allows it to call `AssumeRole` for the specified role).
