### ISSUE TITLE
Path whitelist regex has no effect

### ISSUE THREAD

**Issue by stevenjm** [uswitch/kiam#177]
If I pass `--whitelist-path-regex='.*'` to `kiam agent`, I still get 404s when I try to access any metadata paths aside from the kiam-provided IAM credentials.

Example log message from a kiam agent with `--whitelist-path-regex='.*'`:

```
{"addr":"100.106.0.1:45514","duration":0,"headers":{"Content-Type":["text/plain; charset=utf-8"],"X-Content-Type-Options":["nosniff"]},"level":"info","method":"GET","msg":"processed request","path":"/latest/","status":404,"time":"2018-11-08T13:28:33Z"}
```

This does not contain the "request blocked" message from https://github.com/uswitch/kiam/blob/v3.0-rc3/pkg/aws/metadata/handler_proxy.go#L51. I cannot tell whether this is because the wrong request handler is being used, or because this error message isn't propagated by the caller.

**Comment by pingles** [comment]
Yep- was a bug, thanks for reporting @stevenjm.

**Comment by pingles** [comment]
Given the importance of this I've tagged another build, it's up at `quay.io/uswitch/kiam:v3.0-rc4` now.

**Comment by jaygorrell** [comment]
For anyone else landing here trying to find documentation on the whitelist flag, it's actually called `whitelist-route-regexp` (not `whitelist-path-regex`), and the quotes around the `'.*'` above will not work as expected.

**Comment by seanlarge** [comment]
Working with helm, I have set the whitelist regex like so: 

``` 
agent:
    host:
      iptables: true
      interface: lxc+
      whiteListRouteRegexp: {
         "/latest/meta-data/spot/*"
    } 
```

but my requests are still blocked by KIAM:

```
{"addr":"10.217.3.200:33510","level":"error","method":"GET","msg":"error processing request: request blocked by whitelist-route-regexp \"^$\": /latest/meta-data/spot/termination-time","path":"/latest/meta-data/spot/termination-time","status":404,"time":"2019-10-16T17:37:48Z"}
{"addr":"10.217.3.200:33510","duration":0,"headers":{"Content-Type":["text/plain; charset=utf-8"],"X-Content-Type-Options":["nosniff"]},"level":"info","method":"GET","msg":"processed request","path":"/latest/meta-data/spot/termination-time","status":404,"time":"2019-10-16T17:37:48Z"}
```

maybe my path is off?
