### ISSUE TITLE
Fix metric naming /Grafana Dashboard

### ISSUE THREAD

**Issue by Joseph-Irving** [uswitch/kiam#187]
We have a few metrics that seem to be incorrectly called 
`kiam_metadata_handler_latency_milliseconds`
`kiam_sts_assumerole_timing_milliseconds`
despite being in seconds. Which is causing some confusion.

Also on the example dashboard Credentials/rolehandler response time graphs don't seem to be showing what their name would suggest, it's doing a sum(irate(histogram_bucket)) which does not give you the response times in seconds. I'm not exactly sure what that does give you.

As this is a histogram it would make more sense to plot things like 90, 95, 99th percentile etc e.g: `histogram_quantile(0.95, sum(rate(kiam_metadata_handler_latency_milliseconds_bucket[5m])) by (le))`

We could also calculate the average response time with
`rate(kiam_metadata_handler_latency_milliseconds_sum[5m])/rate(kiam_metadata_handler_latency_milliseconds_count[5m])`

**Comment by pingles** [comment]
https://godoc.org/github.com/prometheus/client_golang/prometheus#Timer.ObserveDuration appears to justify the milliseconds/seconds:

> ObserveDuration records the duration passed since the Timer was created with NewTimer. It calls the Observe method of the Observer provided during construction with the duration in seconds as an argument.

**Comment by pingles** [comment]
I'm going to mark this as something we should resolve before the final v3 release (maybe one more rc on the way 😄); it'll be a huge pain to have to sort this later.

**Comment by pingles** [comment]
Merged so closing the issue.
