### ISSUE TITLE
add rbac

### ISSUE THREAD

**Issue by allandegnan** [uswitch/kiam#19]
The deploy files don't work on an rbac enabled cluster.  From debug logs, it looks like it mostly just needs to do GETs on pods and namespaces.  

Will try and figure out the minimum set and PR a file, just trying to track the things I had to do to get this running. :)

**Comment by pingles** [comment]
Thanks! Yep- it creates caches for pods and namespaces so it only needs to read those (albeit across all namespaces).

**Comment by pingles** [comment]
@allandegnan do you want to try this image and check you can still deploy to your cluster? I've tried on our alpha cluster and it appears to work fine.

If so, you can change your image to `quay.io/uswitch/kiam:rbac` which tracks this branch automatically from our Drone build.

I'll do some more monitoring/testing when I'm back next week before merging.

**Comment by pingles** [comment]
I've merged this in from #23
