### ISSUE TITLE
KIAM server not able to request AWS credentials :  RequestError: send request failed\ncaused by: Post https://sts.amazonaws.com/: x509: failed to load system roots and no roots "

### ISSUE THREAD

**Issue by lp060** [uswitch/kiam#194]
Hi,

"The use case is a fluentd-kinesis is running as daemon set on kube-system namespace we have which runs across all nodes and uses an IAM role to access kinesis"

I have KIAM server running on the master and agent running on the nodes. When the fluentd daemonset tries to assume an IAM role, its sending request for AWS credentials.

Request for AWS credentials is reaching server from agent but 
I am getting error at server end
{"level":"error","msg":"error requesting credentials: RequestError: send request failed\ncaused by: Post https://sts.amazonaws.com/: x509: failed to load system roots and no roots provided","pod.iam.role":"arn:aws:iam::136544107840:role/IKS_kinesis_access","time":"2018-11-27T03:49:33Z"}
{"generation.metadata":0,"level":"error","msg":"error warming credentials: RequestError: send request failed\ncaused by: Post https://sts.amazonaws.com/: x509: failed to load system roots and no roots "

I know that the namespace on which server is running should have permissions "iam.amazonaws.com/permitted":".*" and hence added the same as an annotation to kube-system namespace.

I am not sure what the issue is. Please help me in resolving the issue

Please find below my server.yaml and agent.yaml

agent.yaml - `apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  namespace: kube-system
  name: kiam-agent
spec:
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9620"
      labels:
        app: kiam
        role: agent
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      nodeSelector:
        kubernetes.io/role: node
      #tolerations:
      #- effect: NoExecute
      #  operator: Exists
      #- effect: NoSchedule
      #  operator: Exists
      volumes:
        - name: ssl-certs
          hostPath:
            path: /etc/ssl/certs
        - name: tls
          secret:
            secretName: kiam-agent-tls
        - name: xtables
          hostPath:
            path: /run/xtables.lock
            type: FileOrCreate
      containers:
        - name: kiam
          securityContext:
            privileged: true
          image: quay.io/uswitch/kiam:master
          imagePullPolicy: Always
          command:
            - /kiam
          args:
            - agent
            - --iptables
            - --host-interface=cali+
            - --json-log
            - --port=8181
            - --cert=/etc/kiam/tls/agent.pem
            - --key=/etc/kiam/tls/agent-key.pem
            - --ca=/etc/kiam/tls/ca.pem
            - --server-address=kiam-server:443
            - --prometheus-listen-addr=0.0.0.0:9620
            - --prometheus-sync-interval=5s
            - --gateway-timeout-creation=5s
          env:
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          resources:
            requests:
              cpu: 10m
              memory: 5Mi
            limits:
              cpu: 200m
              memory: 100Mi
          volumeMounts:
            - mountPath: /etc/ssl/certs
              name: ssl-certs
            - mountPath: /etc/kiam/tls
              name: tls
            - mountPath: /var/run/xtables.lock
              name: xtables
          livenessProbe:
            httpGet:
              path: /ping
              port: 8181
            initialDelaySeconds: 3
            periodSeconds: 3
`
server.yaml - `---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  namespace: kube-system
  name: kiam-server
spec:
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9620"
      labels:
        app: kiam
        role: server
    spec:
      serviceAccountName: kiam-server
      nodeSelector:
        kubernetes.io/role: master
      tolerations:
      - key: "node-role.kubernetes.io/master"
        effect: "NoSchedule"
        operator: "Exists"
      volumes:
        - name: ssl-certs
          hostPath:
            path: /etc/ssl/certs
        - name: tls
          secret:
            secretName: kiam-server-tls
      containers:
        - name: kiam
          image: quay.io/uswitch/kiam:master
          imagePullPolicy: Always
          command:
            - /kiam
          args:
            - server
            - --json-log
            - --bind=0.0.0.0:443
            - --cert=/etc/kiam/tls/server.pem
            - --key=/etc/kiam/tls/server-key.pem
            - --ca=/etc/kiam/tls/ca.pem
            - --role-base-arn-autodetect
            - --sync=1m
            - --prometheus-listen-addr=0.0.0.0:9620
            - --prometheus-sync-interval=5s
          volumeMounts:
            - mountPath: /etc/ssl/certs
              name: ssl-certs
            - mountPath: /etc/kiam/tls
              name: tls
          resources:
            requests:
              cpu: 50m
              memory: 10Mi
            limits:
              cpu: 200m
              memory: 200Mi
`

**Comment by lp060** [comment]
I have taken the kiam image from the quay.io/uswitch/kiam:master and the mount path in the yaml file is /etc/ssl/certs. what is the meaning of shared TLS certificates. I generated the certs by taking samples from docs folder.

**Comment by Joseph-Irving** [comment]
If you look at the example deploy here https://github.com/uswitch/kiam/blob/master/deploy/server.yaml#L20 there are two certs volumes being created. One is the tls certs that you generate yourself, the other is the host machines ca-certificates, https://github.com/uswitch/kiam/blob/master/deploy/server.yaml#L46 these are then mounted into /etc/kiam/tls and ets/ssl/certs respectively. 

This is because the Kiam image is built from scratch, so it has no ca-certificates, so to trust the AWS cert it needs a ca-cert to be provided, this is most easily done just by mounting in your hosts trusted CAs.

**Comment by pingles** [comment]
I'm going to close this issue- @lp060 if you still have problems please reply/join on Slack for more help, although @Joseph-Irving's suggestion should sort the problem.

**Comment by lp060** [comment]
Thank you so much for the explanation!! Its working now after I changed the host mount path to /etc/pki/ca-trust/extracted/pem/

**Comment by kostyrev** [comment]
for ubuntu 16.04 hostPath `/usr/share/ca-certificates/mozilla` worked.
