### ISSUE TITLE
kiam agent init time and pod waiting for ready state

### ISSUE THREAD

**Issue by dwjft** [uswitch/kiam#203]
Our services have a lot of auto-scaling for burst processing, which means we are constantly spinning up new nodes and destroying them. Of course, as part of the process to spin up our node, we initialize a kiam-agent for our pods on that node to use.

Is there a way to have our pods not create until the kiam-agent is ready? Currently, spinning our pods seems to be asynchronous alongside the initialization of the kiam-agent, which causes some issues with needing to access aws services upon pod start.

Apologies if this isn't the correct place to ask this question, but it seems like something other people may have stumbled across.

**Comment by Joseph-Irving** [comment]
So Kubernetes should always schedule Daemonsets first as they tolerate all the various not-ready node taints. However it is possible for other pods to start getting scheduled on your node after the node is ready but the Kiam-agent is still initialising which can cause issues.

A way you could potentially get around this is by having your nodes start up with a noschedule taint of something along the lines of `node.kubernetes.io/kiam-not-ready` which then gets removed once Kiam is ready, thus preventing any pods that don't tolerate that taint being scheduled until that happens.

**Comment by dwjft** [comment]
Thanks for the response!

For some clarity, are you saying we would have to create the entire process around adding / removing the taint, or does the kiam-agent already remove that taint from pods on the node?

**Comment by Joseph-Irving** [comment]
Yeah it's not something Kiam currently does. I don't know if it would be worth baking into kiam itself as we have plans in the future to look at turning KIAM into a sidecar model which would get around the this problem anyway.

**Comment by dwjft** [comment]
Okay, cool. Thanks again for the insight.

Looks like our best option is to bake in a retry interval when connecting to AWS. Any ETA on when the sidecar approach may be preferred?

**Comment by dwjft** [comment]
If anyone else comes across this issue, the aws sdk offers a credentials type of `EC2MetadataCredentials` that you can implement with timeouts and retries.

JS version: https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/EC2MetadataCredentials.html

**Comment by Joseph-Irving** [comment]
We'd like to get it done soon, but I don't have any ETA on it. We've only done some high level design of what it might look like so far but hopefully we'll start making some progress on it.

**Comment by dwjft** [comment]
So I tried with the timeouts in the sdk and they don't work because the IP is responding with an `ECONNREFUSED` message, instead of a timeout or try again.

I'm struggling to think of a permanent work-around other than to have the applications `sleep(10);` at boot up so the kiam-agent has the time it needs to come alive.

Is it possible to configure the node / agent to respond to aws IP address requests with a different response that would allow the SDKs to retry intermittently rather than just being refused and shutting down?

**Comment by jpugliesi** [comment]
@dwjft Did you find a solution to address this? We're facing the same issue of a race between kiam-agent and an application pod on a newly started autoscaled node

**Comment by dwjft** [comment]
Unfortunately not. The gross solution of just sleeping is the best. 

@jpugliesi
