### ISSUE TITLE
Kiam agent crashing on one node, working on another

### ISSUE THREAD

**Issue by golgoth** [uswitch/kiam#210]
Hi!
I set up kiam 3.0 on my EKS cluster, 2 nodes are hosting the servers, and 2 others are hosting agents. 
When deploying kiam 2.7, I had no problem, however when deploying 3.0, I couldn't get the agents to work.

I was getting:
```{"level":"info","msg":"configuring iptables","time":"2019-01-21T12:08:22Z"}
INFO: 2019/01/21 12:08:22 parsed scheme: "dns"
{"level":"info","msg":"started prometheus metric listener 0.0.0.0:9090","time":"2019-01-21T12:08:22Z"}
INFO: 2019/01/21 12:08:27 grpc: failed dns TXT record lookup due to lookup release-kiam-server on 172.20.0.10:53: dial udp 172.20.0.10:53: operation was canceled.
{"level":"fatal","msg":"error creating server gateway: error dialing grpc server: context deadline exceeded","time":"2019-01-21T12:08:27Z"}
```

After several retries, I managed to get one agent pod running fine:
```{"level":"info","msg":"configuring iptables","time":"2019-01-21T11:36:43Z"}
{"level":"info","msg":"started prometheus metric listener 0.0.0.0:9090","time":"2019-01-21T11:36:43Z"}
INFO: 2019/01/21 11:36:43 parsed scheme: "dns"
INFO: 2019/01/21 11:36:43 grpc: failed dns TXT record lookup due to lookup release-kiam-server on 172.20.0.10:53: no such host.
INFO: 2019/01/21 11:36:43 ccResolverWrapper: got new service config: 
WARNING: 2019/01/21 11:36:43 grpc: parseServiceConfig error unmarshaling  due to unexpected end of JSON input
INFO: 2019/01/21 11:36:43 ccResolverWrapper: sending new addresses to cc: [{100.64.64.150:443 1 100-64-64-150.release-kiam-server.default.svc.cluster.local. <nil>} {10.19.66.197:443 1 10-19-66-197.release-kiam-server.default.svc.cluster.local. <nil>} {10.19.66.197:443 0  <nil>} {100.64.64.150:443 0  <nil>}]
INFO: 2019/01/21 11:36:43 base.baseBalancer: got new resolved addresses:  [{100.64.64.150:443 1 100-64-64-150.release-kiam-server.default.svc.cluster.local. <nil>} {10.19.66.197:443 1 10-19-66-197.release-kiam-server.default.svc.cluster.local. <nil>} {10.19.66.197:443 0  <nil>} {100.64.64.150:443 0  <nil>}]
INFO: 2019/01/21 11:36:43 base.baseBalancer: handle SubConn state change: 0xc420446780, CONNECTING
INFO: 2019/01/21 11:36:43 base.baseBalancer: handle SubConn state change: 0xc4204467a0, CONNECTING
INFO: 2019/01/21 11:36:43 base.baseBalancer: handle SubConn state change: 0xc4204467c0, CONNECTING
INFO: 2019/01/21 11:36:43 base.baseBalancer: handle SubConn state change: 0xc4204467f0, CONNECTING
INFO: 2019/01/21 11:36:43 base.baseBalancer: handle SubConn state change: 0xc4204467f0, READY
INFO: 2019/01/21 11:36:43 roundrobinPicker: newPicker called with readySCs: map[{100.64.64.150:443 0  <nil>}:0xc4204467f0]
```
but the second pod still crashes with the same log output as mentioned above. 
The next deployment, none were working anymore, 

My server.json file is made for supporting both versions (I release with helm, and the helm release name is `release`):
```
{
    "hosts": [
        "release-kiam-server",
        "release-kiam-server:443",
        "127.0.0.1:443",
        "127.0.0.1"
],
    "key": {
        "algo": "rsa",
        "size": 2048
    },
    "names": [
        {
            "C":  "UK",
            "L":  "London",
            "O":  "uSwitch",
            "OU": "WWW",
            "ST": "London"
        }
    ]
}
```

That's all the logs I get with setting the 'info' env variables. Any idea what I could be doing wrong? The server pods are always working fine.

**Comment by pingles** [comment]
It appears to be a connection issue between the agent and server. I'd check whether you have any network policy, security groups, firewall rules etc. that could be affecting things.

Make sure you keep the gRPC debug output and you can verify that the resolution of the server is being performed by the agent. For example, below you'll see that it's finding the server's address.

```INFO: 2019/01/21 11:36:43 roundrobinPicker: newPicker called with readySCs: map[{100.64.64.150:443 0  <nil>}:0xc4204467f0]
```

That service IP looks suspiciously like a virtual IP though- I'd expect instead that to be a set of Pod IPs for the different server processes rather than a single VIP.

**Comment by golgoth** [comment]
That IP is from the subnet I use, EKS uses those IPs afaik.
The thing is, with kiam 2.7 on the exact same cluster/nodes, everything works totally fine, which excludes networking problems. shouldn't it?

The second logs I sent, which were for the working agent, were not stopping there, alas I don't have them anymore. Everytime I try to start v3.0, all my agents fail. This was a rare case where one made it through.

**Comment by golgoth** [comment]
It seems that after crashing 2-3 times the pods are now working, I don't know what changed though! Closing this!
