### ISSUE TITLE
Reissuing certs causes kiam-agent outage

### ISSUE THREAD

**Issue by 2rs2ts** [uswitch/kiam#211]
I am using kiam 2.7 on kubernetes 1.13.2, and to prep to upgrade for kiam 3.0 I updated my certs to support the extra names that the upgrade doc says to support, reissued them and updated the Secrets in k8s. Soon after, all my users reported that they couldn't get their sts credentials, and I saw messages like this in the agent logs:

```
kiam-agent-v22wz kiam {"level":"warning","msg":"error finding role for pod: rpc error: code = Unavailable desc = there is no connection available","pod.ip":"192.168.104.67","time":"2019-01-28T21:07:02Z"}
```

I also see that a liveness probe failed on the kiam-server pods but it happened well over half an hour after the Secrets were updated. I can't find any logs during this timeframe that indicate why kiam-server's probe failed.

The only way to fix this was to cycle the kiam-agent pods, which is not hitless. Unfortunately this leaves me in a very uncomfortable position because I can't finish reissuing the certs.

All signs point to kiam-server doing something to detect when its certs Secret is updated. If this causes outages that's not acceptable. Can you backport a fix to 2.7?

**Comment by 2rs2ts** [comment]
BTW I can reproduce this reliably by reissuing the certs, I even reverted to the old list of names and this still happens

**Comment by pingles** [comment]
It sounds like it's possible by supporting a callback handler: https://github.com/grpc/grpc/issues/10528#issuecomment-403102673.

**Comment by 2rs2ts** [comment]
Well we ended up just upgrading to 3.0 anyways and it doesn't have this problem so I'm going to close this
