### ISSUE TITLE
Delete repository on Docker Hub

### ISSUE THREAD

**Issue by myniva** [uswitch/kiam#221]
The official images of KIAM are hosted on https://quay.io/repository/uswitch/kiam. Some outdated images are still available via a similar repository on Docker Hub: https://hub.docker.com/r/uswitch/kiam

I suggest that the repository on Docker Hub is deleted to avoid confusion.

**Comment by Joseph-Irving** [comment]
I think I'd rather make it more obvious that Kiam is on quay instead of deleting the docker hub ones. It's probably very unlikely, but there could well be people using those images on docker hub so if we just delete them it could cause all their kiam deployments to fail.

**Comment by myniva** [comment]
Good point, you shoulnd't make it harder for your users as absolutely needed.

The issue I was facing was that I instinctively did something like `docker pull uswitch/kiam` which ended up downloading `latest` from Docker Hub. So you might want to consider removing at least the `latest` tag from Docker Hub.

**Comment by Joseph-Irving** [comment]
Removing latest still has the same problem of someone could be using it (they probably shouldn't be but that's a different debate)
