### ISSUE TITLE
livenessProbe on agent don't detect server issues

### ISSUE THREAD

**Issue by caiohaz** [uswitch/kiam#226]
Today i updated a my helm chart and the kiam-server broke, no problems because i forgot a parameter and fix, but the problem is that kiam-agent "lost" the kiam-server connection and doesn't work anymore, the error on message is:

> {"addr":"100.116.115.230:52788","level":"error","method":"GET","msg":"error processing request: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = \"transport: Error while dialing dial tcp 100.105.75.193:443: connect: connection refused\"","path":"/latest/meta-data/iam/security-credentials/","status":500,"time":"2019-03-05T12:26:28Z"}
{"addr":"100.116.115.230:52788","duration":1001,"headers":{"Content-Type":["text/plain; charset=utf-8"],"X-Content-Type-Options":["nosniff"]},"level":"info","method":"GET","msg":"processed request","path":"/latest/meta-data/iam/security-credentials/","status":500,"time":"2019-03-05T12:26:28Z"}

I think that is not a problem because kiam-server had a error, but i think that livenessProbe would have to detect this problem and restart the kiam-agent, right? Currently i'm using this livenessProbe:

> livenessProbe:
  httpGet:
    path: /ping
    port: 8181
  initialDelaySeconds: 3
  periodSeconds: 3

Regards

**Comment by Joseph-Irving** [comment]
I don't think this is necessarily a problem with the liveness probe, you wouldn't want all your kiam agents to get liveness killed if your servers go down as that doesn't achieve much. 
Did your kiam agents not recover by themselves? I would've expected them to start working correctly once the kiam servers were back up.

**Comment by caiohaz** [comment]
Hi @Joseph-Irving ,

Hmm yes, you are right. I can't confirm if is i all situations the agent don't recover themselves, but i see the problem happening lot's of, and when the problem happened the simple agent pod restart solved.

Regards

**Comment by caiohaz** [comment]
@Joseph-Irving ?

**Comment by Joseph-Irving** [comment]
Hi @caiohaz, what version of kiam are you using?
If you can paste the output of the logs on the agent around the time this happens and it subsequently not recovering that would be helpful. Also if this coincides with errors from the kiam-server.

**Comment by caiohaz** [comment]
Hi @Joseph-Irving Ok, i will upgrade the kiam to new release (v3.2) and test again, if i found some problem i will collect these logs and reopen the issue, ok?
