### ISSUE TITLE
External_ID Support for Cross account IAM Role

### ISSUE THREAD

**Issue by abhisheknsit** [uswitch/kiam#236]
AWS IAM supports external id as a security measure for cross account IAM roles.
Ref: https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_create_for-user_externalid.html

Issue for enhancement to add support for external id in KIAM.

**Comment by randomvariable** [comment]
Unless there's anyone else planning to do this, am willing to take this one.

**Comment by randomvariable** [comment]
In terms of UX, any objection to doing it as an additional annotation, in the form of an `iam.amazonaws.com/external-id` annotation?

**Comment by harishspqr** [comment]
Given that external ID is kind of like a password, from security perspective will it make sense to add it as a secret and mount it on to a user pod instead of having it in clear text in the pod manifests ?

**Comment by randomvariable** [comment]
Apologies for the delay. This is in progress.

**Comment by Lokicity** [comment]
Hi, is there an ETA for this work? We would love the support for external_ID.

**Comment by pingles** [comment]
It's being worked on at the moment, and aiming to be part of a v4 release soon.

**Comment by pingles** [comment]
This was merged earlier today in #430.
