### ISSUE TITLE
Kiam agent running into CrashLoopBackOff with version 3.0 and 3.2

### ISSUE THREAD

**Issue by RaviHari** [uswitch/kiam#237]
I tried creating a k8s (k8s serversion 1.12) cluster..  but ran into this issue when using kiam version 3.0 and version 3.2:
Error: failed to start container "kiam": Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "exec: \"/agent\": stat /agent: no such file or directory": unknown

However it works with kiam v2.7.

**Comment by Joseph-Irving** [comment]
Yeah in kiam 3.0 the server and agent commands are combined into one binary so you run `/kiam server` or `/kiam agent` e.g https://github.com/uswitch/kiam/blob/master/deploy/server.yaml#L33

**Comment by RaviHari** [comment]
after using the latest manifests I am getting the following issue:
Back-off restarting failed container and kiam-agent is in CrashLoopBackOff

with these configs..

    Command:
      /kiam
    Args:
      agent
      --iptables
      --host-interface=cali+
      --json-log
      --port=8181
      --cert=/etc/kiam/tls/agent.pem
      --key=/etc/kiam/tls/agent-key.pem
      --ca=/etc/kiam/tls/ca.pem
      --server-address=kiam-server:443
      --prometheus-listen-addr=0.0.0.0:9620
      --prometheus-sync-interval=5s
      --gateway-timeout-creation=2s
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1

**Comment by DewaldV** [comment]
@RaviHari 
Can you confirm that your `kiam-server` pods are running and ready? This looks like an agent that can't connect to the `kiam-master`?

**Comment by RaviHari** [comment]
kiam-server is not running

**Comment by RaviHari** [comment]
@pingles I donot see the pods for kiam-server even coming up.. to capture the logs I only see kiam-agent pods..

**Comment by RaviHari** [comment]
I see this error during cluster creation for kiam-server.. 

kiam MainThread: Exception when calling CoreV1Api->read_namespaced_secret: kiam-server-tls
(404)
Reason: Not Found
HTTP response headers: HTTPHeaderDict({'Audit-Id': '945fff02-63a2-4edf-9713-8d4d25cff0f9', 'Content-Type': 'application/json', 'Date': 'Mon, 01 Apr 2019 17:57:37 GMT', 'Content-Length': '204'})
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"secrets \"kiam-server-tls\" not found","reason":"NotFound","details":{"name":"kiam-server-tls","kind":"secrets"},"code":404}

**Comment by RaviHari** [comment]
after increasing --gateway-timeout-creation in kiam-server health check to 60s and in kiam-agent to 90s I see this log in kiam-agent:
Liveness probe failed: Get http://<IP>:8181/ping: dial tcp <IP>:8181: connect: connection refused

**Comment by pingles** [comment]
Your earlier error is the issue- the server pod is referencing a secret
that doesn't exist, so I'd check if you created those successfully/whether
there's a typo in the name etc

**Comment by RaviHari** [comment]
after looking deep into this.. I see  the following logs

Exception when calling CoreV1Api->read_namespaced_secret: kiam-server-tls
(404)
Reason: Not Found
HTTP response headers: HTTPHeaderDict({'Audit-Id': '706c2237-b1e0-44d7-9897-d20bbbe978ee', 'Content-Type': 'application/json', 'Date': 'Tue, 02 Apr 2019 04:02:14 GMT', 'Content-Length': '204'})
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"secrets \"kiam-server-tls\" not found","reason":"NotFound","details":{"name":"kiam-server-tls","kind":"secrets"},"code":404}

Executing: kubectl apply --context=kiam-test.cluster.k8s.local --filename /tmp/tmpszffby0o.yml secret/kiam-server-tls created
MainThread: Submitted KIAM secrets
MainThread: Submitting KIAM manifests
MainThread: Installing addon of type 'v1/ServiceAccount'
MainThread: Executing: kubectl apply --context=kiam-test.cluster.k8s.local --filename /tmp/tmpfw4unywy.yml serviceaccount/kiam-server created


it looks like the kiam-server and kiam-server-tls secrets etc., are getting created... but i donot see the kiam-server pod running..

**Comment by pingles** [comment]
What do you see when you `kubectl get pods` and `kubectl get secrets` in the namespace where kiam is running? It looks like `kiam-server-tls` doesn't exist where the server is expecting to find it.

**Comment by RaviHari** [comment]
I see this:
kubectl get pods,secrets -n kube-system|grep kiam

pod/kiam-agent-vp72l                                                        1/1     Running   99         5h8m
secret/kiam-agent-tls                                   Opaque                                3      5h9m
secret/kiam-server-tls                                  Opaque                                3      5h9m
secret/kiam-server-token-zj67r                   kubernetes.io/service-account-token   3      5h9m

they are all in same namespace kube-system but for some reason kiam-server doesnot comeup

**Comment by pingles** [comment]
Do you have any RBAC controls that may be inhibiting the server's service account from accessing the secret?

**Comment by RaviHari** [comment]
Nothing specific.. I am using: https://github.com/uswitch/kiam/blob/master/deploy/server-rbac.yaml

**Comment by RaviHari** [comment]
@pingles also as mentioned in the logs above it couldnot find it the first time.. but it created secret after that.. still kiam-server is not coming up

**Comment by pingles** [comment]
I'd check the output of `kubectl get ds`: the lack of a server pod suggests that the daemonset isn't scheduling anything (assuming that's the config you're applying straight from the repo). @jbeda hit this during the TGIK.

@Joseph-Irving remember the taints/tolerations that were changed to sort?

**Comment by pingles** [comment]
@RaviHari if you watch Joe Beda's recent TGIK where he setup Kiam you'll see him run some commands to try and understand why the server processes weren't starting (and would probably be useful for you to follow too): https://www.youtube.com/watch?v=vgs3Af_ew3c.

**Comment by RaviHari** [comment]
Thanks @pingles the server is coming up now after adding right node selctor and toleraitons.
But i am running into this issue when trying to access s3 bucket from pod.. (but it works from master nodes)

{"generation.metadata":0,"level":"error","msg":"error retrieving credentials: AccessDenied: Access denied\n\tstatus code: 403, request id: 3990533a-627b-11e9-b240-891548b8ceed","pod.iam.requestedRole":"test-s3-iam-roles","pod.iam.role":"test-s3-iam-roles","pod.name":"aws","pod.namespace":"default","pod.status.ip":"x.x.x.x","pod.status.phase":"Running","resource.version":"1909691","time":"2019-04-19T08:14:59Z"}
{"level":"error","msg":"error requesting credentials: RequestCanceled: request context canceled\ncaused by: context canceled","pod.iam.role":"test-s3-iam-roles","time":"2019-04-19T08:20:25Z"}
{"generation.metadata":0,"level":"error","msg":"error retrieving credentials: context canceled","pod.iam.requestedRole":"test-s3-iam-roles","pod.iam.role":"test-s3-iam-roles","pod.name":"aws","pod.namespace":"default","pod.status.ip":"x.x.x.x","pod.status.phase":"Running","resource.version":"y","time":"2019-04-19T08:20:25Z"}

**Comment by RaviHari** [comment]
I got thhis fixed i had to add --assume-role-arn=<kiam-server-role-arn> in server.yaml to fix this.. 
or allow the s3 role to trust master directly.. it worked in both the cases.

Thanks for all the help.
