### ISSUE TITLE
Assign multiple roles to a Pod

### ISSUE THREAD

**Issue by arpitairan** [uswitch/kiam#242]
Hello, I have a question about an implementation strategy with KIAM.

There are two AWS accounts AWS1 & AWS2. An application "podApp" is running in AWS1.
We want the "podApp" to have access to some resources from AWS1 (in which it is running) and also to S3 and SQS services from AWS2 (To send data to another K8s cluster in AWS2).

How can we achieve this with KIAM as we are only able to assign role from either AWS1 or AWS2?

Could anyone please help us asap as this is blocking us from using KIAM?

**Comment by Joseph-Irving** [comment]
You can grant an IAM role in one aws account access to resources in a different aws account for an example with sqs see [here].(https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-customer-managed-policy-examples.html#grant-cross-account-permissions-to-role-and-user-name).  So you can use one role with access to resources in both aws accounts.

**Comment by arpitairan** [comment]
Hello Joseph,

Thank you for your reply.
Resource based policy helped in case of the S3 however, I am still getting below error with SQS -

________________________________________

com.amazonaws.AmazonServiceException: Access to the resource https://sqs.us-west-2.amazonaws.com/ is denied. (Service: AmazonSQS; Status Code: 403; Error Code: AccessDenied;

________________________________________

I have attached the following Resource Based policy to SQS queue to which I want access to in AWS2.

{
  "Version": "2012-10-17",
  "Id": "arn:aws:sqs:us-west-2:AWS2:queuename/SQSDefaultPolicy",
  "Statement": [
    {
      "Sid": "SID1",
      "Effect": "Allow",
      "Principal": {
        "AWS": [
          "arn:aws:iam::AWS1:role/path/podApp",
          "arn:aws:iam::AWS1:role/kiam-server-role",
          "arn:aws:iam::AWS1:role/master-node-role"
        ]
      },
      "Action": "sqs:*",
      "Resource": "AWS2-QueueARN"
    }
  ]
}

I am sure I am missing on adding something in the policy but I am not sure what that could be.

**Comment by abhisheknsit** [comment]
@arpitairan The role you are using should also have permissions to access SQS.
I think in your case, this role: `arn:aws:iam::AWS1:role/path/podApp`
