### ISSUE TITLE
Using KIAM outside AWS

### ISSUE THREAD

**Issue by akervern** [uswitch/kiam#244]
Hi, I have a global question more than an issue, and maybe I miss something really obvious on my side.

I had in mind that Kiam is able to run outside a EKS/EC2 based K8s cluster. I mean, basically, I'd like to use Kiam in a GKE cluster in order to rely on roles per pod.

And, everything I read in your documentation is about EC2 instance role, and I wasn't able to find any obvious parameter to configure a user with API key/secret (or any other smarter way) rather than a role for the server.

Thanks for your help!

**Comment by pingles** [comment]
Kiam intercepts metadata API requests for credentials. It _should_ be possible to make it run elsewhere- it uses the AWS SDK so as long as the server process is able to obtain credentials (`AWS_ACCESS_KEY_ID` env variable for example) it should be able to make `sts:AssumeRole` calls.

Of course no other metadata API calls would succeed but Kiam now defaults to blocking those unless you whitelist using a regexp with the agent.

**Comment by pinkavaj** [comment]
In adition to AWS credentials also `--role-base-arn=arn:aws:iam::XXXXXX:role/` must be set, because it cannot deduced the ARN using metadata API.

But using kiam outside of AWS now does not work, the server silently dies.

**Comment by akervern** [comment]
Cool, thanks for your informations!

**Comment by tlvenn** [comment]
I am trying to make this work as well and the server logs the following error:

```
{"level":"error","msg":"error requesting credentials: SignatureDoesNotMatch: The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.\n\tstatus code: 403, request id: 22fb9d36-98d2-11e9-9fed-47a079d11597","pod.iam.role":"Kube2IAMTest","time":"2019-06-27T11:53:10Z"}
```

Is there any way to see the complete json error from aws ? I am providing the credentials to the server pods with env variables.

**Comment by tlvenn** [comment]
@akervern did you end up getting it to work with GKE ?

**Comment by pinkavaj** [comment]
I managed it working, i hit the issue #243 otherwise works out of box (with setup mentioned above)

**Comment by KevinSnyderCodes** [comment]
We were able to get kiam running in GKE with the suggestions above, but it's incompatible for our use case.

Both AWS and Google Cloud use the same IP address `169.254.169.254` for their Metadata API. When you enable Workload Identity on a GKE cluster it also sets `iptables` rules for that destination IP that have higher priority than the ones kiam creates.

Even if priority wasn't an issue the rules would still be incompatible, as there is no way to tell if a Metadata API request is intended for AWS or Google Cloud.

If you're not using Workload Identity then this will probably work as intended.

We're now exploring [gtoken](https://github.com/doitintl/gtoken) as an alternate solution, which relies on Workload Identity and OIDC to assume AWS IAM roles. The accompanying [blog post](https://blog.doit-intl.com/securely-access-aws-from-gke-dba1c6dbccba) does a good job explaining how it works.

**Comment by danopia** [comment]
As an alternative if you're running under GKE: you can install the EKS pod identity webhook and the AWS SDK will know what to do within each pod. It depends on the OIDC aspect and there's some IAM trust to set up, but it doesn't depend on the metadata server at all so you can run AWS pod identity in parallel with Google workload identity. I use both within the same cluster just fine.

**Comment by bhaveshtank** [comment]
@danopia We tried setting up above SDK is unable to fetch the token, we have done the trust setup using GKE workload identity, GCP service account. We binded GKE serviceaccount to GCP serviceaccount and created a OIDC role setup on AWS.
are we missing something ?
