### ISSUE TITLE
QUESTION: namespace annotation

### ISSUE THREAD

**Issue by axozoid** [uswitch/kiam#247]
HI guys,
Just wanted to confirm, is a namespace annotation must be a regular expression or I could also explicitly specify a role?
In my namespace an app will be restricted to one particular role only (the role is also set in pods' annotations).

Thank you!

**Comment by pingles** [comment]
Yes. The annotation on the namespace is a regular expression and controls which roles can be assumed by Pods running within that namespace. For a pod to assume a role it must have both a role specified on the Pod _and_ be permitted by the namespace regex. If you want to specify a regex in the namespace that only permits the one role that's totally fine also- any valid regex will do.
