### ISSUE TITLE
getting rpc error: code = Unavailable desc = there is no connection available while reinstalling kiam using helm charts

### ISSUE THREAD

**Issue by prshntsingh2010** [uswitch/kiam#251]
This is the issue I get in one of my k8s cluster. 
Kiam version used is 2.7
parsanth@modi-uaa-latest-79f58965cb-7777z:~$ curl -v 169.254.169.254/latest/meta-data/iam/security-credentials/
> Accept: */*
>
< HTTP/1.1 500 Internal Server Error
< Content-Type: text/plain; charset=utf-8
< X-Content-Type-Options: nosniff
< Date: Thu, 23 May 2019 12:34:13 GMT
< Content-Length: 70
<
rpc error: code = Unavailable desc = there is no connection available
* Curl_http_done: called premature == 0
* Connection #0 to host 169.254.169.254 left intact
*   Trying 169.254.169.254...
* TCP_NODELAY set
* Connected to 169.254.169.254 (169.254.169.254) port 80 (#0)
> GET /latest/meta-data/iam/security-credentials/ HTTP/1.1
> Host: 169.254.169.254
> User-Agent: curl/7.52.1
> Accept: */*
>
< HTTP/1.1 500 Internal Server Error
< Content-Type: text/plain; charset=utf-8
< X-Content-Type-Options: nosniff
< Date: Thu, 23 May 2019 12:34:33 GMT
< Content-Length: 70
<
rpc error: code = Unavailable desc = there is no connection available
* Curl_http_done: called premature == 0
* Connection #0 to host 169.254.169.254 left intact

**Comment by prshntsingh2010** [comment]
@pingles can u please help me with this issue?

**Comment by DewaldV** [comment]
@prshntsingh2010 What are the logs from the kiam agent and server saying when encounter this error?

**Comment by prshntsingh2010** [comment]
@DewaldV Hey upgrading Kiam from 2.7 to 3.2 fixed the issue, I will close this issue.
