### ISSUE TITLE
Security Context on the Agent

### ISSUE THREAD

**Issue by chrislovecnm** [uswitch/kiam#27]
I am noticing

```yaml
 securityContext:
            privileged: true
```

Could the container be run without privileged if it did not set up the DNAT rule with iptables?  Or is there another role that can be used that has less root-like permissions?

**Comment by pingles** [comment]
Yep- that would only be used to configure the DNAT rule. I'm not sure about how it'd work with a different role- do you have something that'd help me figure out how to do it? I'd be glad to sort it.

Alternatively, I also thought about an alternate model where all pods were injected with sidecars- they could use iptables (without needing privileged access) and disable outbound metadata api access without doing it on the nodes directly.

The sidecar stuff could potentially go further and run a whole agent as a sidecar but that's probably a topic for another time :)

**Comment by pingles** [comment]
I was thinking about this over the weekend- another option is potentially integrating via ECS' integration: `AWS_CONTAINER_CREDENTIALS_RELATIVE_URI` and https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/index.html?com/amazonaws/auth/ContainerCredentialsProvider.html.

I've not tried it but if I get a chance this week I might give it a whirl!

**Comment by emmanuel** [comment]
I like the idea of removing the requirement for `privileged: true` from the agent, but I don't think that using the ECS credentials distribution model will escape it. It seems that the ECS agent still uses an iptables rule in the host net namespace to redirect a link-local IP (similar to but distinct from the default metadata service link-local ip `169.254.169.254`):
https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task-iam-roles.html#enable_task_iam_roles
Specifically this part:
```
sudo sysctl -w net.ipv4.conf.all.route_localnet=1
sudo iptables -t nat -A PREROUTING -p tcp -d 169.254.170.2 --dport 80 -j DNAT --to-destination 127.0.0.1:51679
sudo iptables -t nat -A OUTPUT -d 169.254.170.2 -p tcp -m tcp --dport 80 -j REDIRECT --to-ports 51679
```
I hope I'm wrong!

**Comment by pingles** [comment]
@emmanuel looks like you're right, that ECS environment variable doesn't set the whole credentials- just the path:

https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-core/src/main/java/com/amazonaws/auth/ContainerCredentialsProvider.java#L94

**Comment by roffe** [comment]
Changing the security context from `privileged: true` on to 

```
          securityContext:
            capabilities:
              add: ["NET_ADMIN"]
```

works fine for me, agent starts fine and does not complain about ip tables

```
jbk/def➜  kiam git:(kube-7) ✗ k logs kiam-agent-kwtlk
{"level":"info","msg":"configuring iptables","time":"2018-06-04T19:11:55Z"}
{"level":"info","msg":"started prometheus metric listener 0.0.0.0:9620","time":"2018-06-04T19:11:55Z"}
{"level":"info","msg":"listening :8181","time":"2018-06-04T19:11:55Z"}
{"addr":"10.0.118.202:38246","headers":{},"level":"info","method":"GET","msg":"processed request","path":"/ping","status":200,"time":"2018-06-04T19:11:58Z"}
```

Double verified the rule actualy gets added as well:

```
root@ip-10-0-118-202:~# iptables -t nat --line-numbers -L PREROUTING

    Chain PREROUTING (policy ACCEPT)
    num  target     prot opt source               destination
    1    DOCKER     all  --  anywhere             anywhere             ADDRTYPE match dst-type LOCAL
    2    DNAT       tcp  --  anywhere             instance-data.eu-west-1.compute.internal  tcp dpt:http to:10.0.118.202:8181

root@ip-10-0-118-202:~# iptables -D PREROUTING 2 -t nat
root@ip-10-0-118-202:~# iptables -t nat --line-numbers -L PREROUTING

    Chain PREROUTING (policy ACCEPT)
    num  target     prot opt source               destination
    1    DOCKER     all  --  anywhere             anywhere             ADDRTYPE match dst-type LOCAL

#restart kiam-agent

root@ip-10-0-118-202:~# iptables -t nat --line-numbers -L PREROUTING

    Chain PREROUTING (policy ACCEPT)
    num  target     prot opt source               destination
    1    DOCKER     all  --  anywhere             anywhere             ADDRTYPE match dst-type LOCAL
    2    DNAT       tcp  --  anywhere             instance-data.eu-west-1.compute.internal  tcp dpt:http to:10.0.118.202:8181

root@ip-10-0-118-202:~#
```

I did not do setcap on the binary in the container

**Comment by roffe** [comment]
It looks like we don't need NET_RAW, the agent is operating as it should, pods on the nodes are getting their credentials served as they should with just NET_ADMIN

from the manpages:
```
CAP_NET_ADMIN
Perform various network-related operations:
*
interface configuration;
*
administration of IP firewall, masquerading, and accounting
*
modify routing tables;
*
bind to any address for transparent proxying;
*
set type-of-service (TOS)
*
clear driver statistics;
*
set promiscuous mode;
*
enabling multicasting;
*
use setsockopt(2) to set the following socket options: SO_DEBUG, SO_MARK, SO_PRIORITY (for a priority outside the range 0 to 6), SO_RCVBUFFORCE, and SO_SNDBUFFORCE.

CAP_NET_RAW
*
use RAW and PACKET sockets;
*
bind to any address for transparent proxying.

**Comment by pingles** [comment]
This is now merged, thanks @roffe.
