### ISSUE TITLE
Running kiam on minikube

### ISSUE THREAD

**Issue by jshaw86** [uswitch/kiam#275]
I'm trying to run Kiam on minikube as a way to authorize secretsmanager requests. I ran into https://github.com/uswitch/kiam/issues/36. Per that ticket there aren't root CA's available. The ticket mentions mounting drives with the root CA's in them which I don't think is possible with minikube or would be cumbersome. Any advice on getting kiam running on minikube?

**Comment by Joseph-Irving** [comment]
I don't see why that wouldn't work with minikube, you should just be able to mount in /etc/ssl/certs for minikube, https://github.com/uswitch/kiam/blob/master/deploy/server.yaml#L27

**Comment by chrisns** [comment]
@Joseph-Irving's (Hey Joe!) suggestion is what I use to test it in minikube, you could if you didn't want `HostPath` mounting and/or wanted to be more explicit inject the CAs via a `ConfigMap` volume mount

**Comment by jshaw86** [comment]
I still haven't been able to get this to work quite right. I'm going to close for now so it doesn't go stale. If I can get more time to investigate and come up with a comprehensive issue report I'll reopen.
