### ISSUE TITLE
Proxy unhandled APIs

### ISSUE THREAD

**Issue by ankon** [uswitch/kiam#3]
When using kiam the complete meta-data service on 169.254.169.254 is replaced, which breaks anything that depends on that -- usually a lot.

Instead the server should proxy all unhandled requests through to the original service.

**Comment by pingles** [comment]
Wow, good catch. I misunderstood how `pat` handles paths. I'm fixing it now :)

**Comment by ankon** [comment]
Awesome!

(Btw, sorry for the issue-spamming: I was so excited to see something that might just fix the kube2iam problems that I just deployed kiam into our cluster ... the issues are basically everything I saw on an extended test drive!)

**Comment by pingles** [comment]
No problem re: issue spamming!

I've tagged the fix in version `v1.1.0` and the image is now on Docker hub also so you should now be able to update your image to `uswitch/kiam:v1.1.0`.
