### ISSUE TITLE
Helm charts

### ISSUE THREAD

**Issue by pingles** [uswitch/kiam#30]
It'd be nice to make it really easy for people to deploy with Helm. I suspect a prerequisite for this would be #29.

**Comment by pingles** [comment]
I'm going to follow-up my opening this issue and say that if anyone more familiar with Helm/Draft would help in contributing this I'd be delighted to help.

**Comment by ewbankkit** [comment]
I have been working on this, https://github.com/uswitch/kiam/pull/53 just submitted.
It is still a WIP but I should get time to continue this week.

**Comment by ewbankkit** [comment]
@pingles This issue has now been superseded by https://github.com/kubernetes/charts/issues/5329.

**Comment by pingles** [comment]
Fantastic, thank you so much for picking this up!

**Comment by ewbankkit** [comment]
@pingles The Helm chart has been merged as stable - https://github.com/kubernetes/charts/pull/5330.
