### ISSUE TITLE
Clarify helm source of truth

### ISSUE THREAD

**Issue by jeffb4** [uswitch/kiam#301]
The helm/charts/stable/kiam chart has continued to see maintenance alongside the uswitch/kiam/helm chart. If the former is deprecated in favor of the in-repo chart, would it be possible to request it be removed from `helm/charts/stable` ? It's a bit confusing (evidenced by my submitting a PR to bump kiam version for the `helm/charts/stable/kiam` chart)

**Comment by rhysemmas** [comment]
Hi @jeffb4, the process to have the old `stable/kiam` chart deprecated in the Helm repo has been started by @ewbankkit: https://github.com/helm/charts/issues/16664

There is currently a PR open to add a pre-deprecation notice to that chart: https://github.com/helm/charts/pull/16668 - hopefully once this PR is merged, the process of having the `stable/kiam` chart deprecated will move along.

In the meantime, please raise any PRs for the Kiam Helm chart against this repo, thanks.

**Comment by ewbankkit** [comment]
A quick update.
The pre-deprecation notice in the Helm repo has just been merged.
There are a few open issues and PRs in that repo that I will wait to either be closed by their owners or go stale before completing the final deprecation steps.

**Comment by jeffb4** [comment]
Awesome thanks! Closing this issue :)
