### ISSUE TITLE
Getting an error on the KIAM Server  pod

### ISSUE THREAD

**Issue by vishalmaheswari** [uswitch/kiam#312]
Getting an error on the KIAM Server  pod

{"generation.metadata":0,"level":"error","msg":"error warming credentials: RequestError: send request failed\ncaused by: Post https://sts.amazonaws.com/: x509: certificate signed by unknown authority",

Do we know whats causing this.

**Comment by japzio** [comment]
distro dependent, below works for ubuntu :

```
server:
    sslCertHostPath: /etc/ssl/certs
```
