### ISSUE TITLE
Unable to limit by IAM path on namespace with RoleBaseARN

### ISSUE THREAD

**Issue by leosunmo** [uswitch/kiam#326]
All of my Kubernetes workloads have roles created under the IAM path `workloads`. I am running in to an issue where I can't use regex to require `/workloads/.*` prefix on the roles to be assumed.
The problem I think I am running in to is the `role-base-arn` isn't appended until _after_ the policy check.

Here's my current setup.

The role I am trying to assume in my Pod is `arn:aws:iam::1234567890:role/workloads/my-amazing-role`

The Kiam server has a role base ARN set
```
--role-base-arn=arn:aws:iam::1234567890:role/workloads/
```

My namespace has the following regex:
```
annotations:
  iam.amazonaws.com/permitted: .*workloads/.*
```

and finally my test pod has this config:
```
annotations:
  iam.amazonaws.com/role: my-amazing-role
```
This looks like it should work from looking at how the `role-base-arn` and `iam.amazonaws.com/permitted` config works.

The server gives me the following error:
```
  Warning  KiamRoleForbidden  8s    kiam.serve    failed assuming role "my-amazing-role`": namespace policy expression '.*workloads/.*' forbids role 'my-amazing-role'`
```

It looks like the full ARN is not resolved at the time of policy evaluation. I think I found the fix in the following old issue, https://github.com/uswitch/kiam/issues/75. @roffe's fix at the end of that issue _should_ fix my issue.
The fix is at https://github.com/roffe/kiam/blob/5f04cecbef761bc0a6a3ba5141497c1ff9585c54/pkg/server/policy.go#L149 but was never merged in to master, https://github.com/uswitch/kiam/blob/master/pkg/server/policy.go#L149.

As far as I understand this means it evaluates the "role" that the Pod annotation provides against the regex in the namespace, not the expanded/resolved role ARN.

**Comment by leosunmo** [comment]
Just made a quick hack and got it to work.

Fork: https://github.com/uswitch/kiam/compare/master...leosunmo:arn-resolve-before-policycheck
Docker image that is working in my environment right now: https://hub.docker.com/repository/docker/leosunmo/kiam

I have not fixed the tests yet as I am not as familiar with how these tests are written. I'll try to take a look as soon as possible.

**Comment by leosunmo** [comment]
PR brought in line with Master and tests have been written.

**Comment by leosunmo** [comment]
Any chance of having this looked at? I'd really like to move away from running a fork in my production environment!

**Comment by pingles** [comment]
I pulled #327 in as part of #435 so all merged. Main has a few breaking changes (flags are different and more) so if you want to test early please do but we don't have upgrade notes just yet. Thanks again for contributing and reporting the issue.
