### ISSUE TITLE
--region is too strict with validating region names

### ISSUE THREAD

**Issue by cjbradfield** [uswitch/kiam#350]
Currently newRegionalResolver validates the region name passed in via the AWS SDK by calling endpoints.PartitionsForRegion().

The problem with this approach is if a new region is introduced that doesn't match the regex of the SDK version kiam is using, the kiam project has to upgrade the AWS SDK before regional STS endpoints can be used in that region.

Instead, kiam should only rely on DNS resolution of the STS endpoint for region validation.

**Comment by pingles** [comment]
I think this is a great point. #368 highlights an issue with the endpoint resolution, so probably worth overhauling. Would love PRs for it 😄

**Comment by pingles** [comment]
I've updated the code and changed it so that we don't check regions but instead follow a pattern. In future potentially we could change to just specify the endpoint.

It's in main at the moment but will be released in v4 when we've closed a few other things out.

Thanks for reporting @cjbradfield

**Comment by cjbradfield** [comment]
Thanks! Sorry I wasn't able to get around to this myself.
