### ISSUE TITLE
How to figure out the version of Kiam running in a cluster

### ISSUE THREAD

**Issue by sagardesai0094** [uswitch/kiam#373]
I have several clusters that are already running kiam, but I am not sure what the version is. I have tried describing the daemonset and pods, but don't see anything related to the kiam version there. I have also tried going into one of the pods and invoking the binary to find out the version, but didn't see any options for that either.

Describing one of the pods shows the following:
```
Containers:
  kiam:
    Container ID:  docker://aa61f47a87820cf86155ad9dc334a8609469d0b6074d4f14022b487d1584971d
    Image:         quay.io/uswitch/kiam:master
    Image ID:      docker-pullable://quay.io/uswitch/kiam@sha256:43f8de51ebde2948382d0b612043b3c7d5b25a6ffbcc6fe08b55027adf87f66e
```

Thanks.

**Comment by Joseph-Irving** [comment]
You're not running a tagged version of kiam `quay.io/uswitch/kiam:master` this is whatever's in our master branch, this is highly discouraged for production use, you should use a tagged version from our https://github.com/uswitch/kiam/releases

**Comment by sagardesai0094** [comment]
Yes, I realized this when I tried to find out the version of kiam from the
image. Unfortunately I don't have the freedom to change things in these
clusters at the moment. Is there any other way to determine the version of
kiam?

**Comment by sagardesai0094** [comment]
Ultimately, I couldn't find a way. If you there is way please post it here, otherwise feel free to post it here.

**Comment by leosunmo** [comment]
@sagardesai0094 
If you `kubectl exec` in to the container and run `kiam agent --help` and see a bunch of GRPC KeepAlive settings it's v3.5, if not, it's v3.4 or below.

```
 --grpc-keepalive-time-ms=10s   gRPC keepalive time
  --grpc-keepalive-timeout-ms=2s
                                 gRPC keepalive timeout
  --grpc-keepalive-permit-without-stream
                                 gRPC keepalive ping even with no RPC
```
