### ISSUE TITLE
Empty role error when annotation is only set in the namespace

### ISSUE THREAD

**Issue by mo-saeed** [uswitch/kiam#391]
I am getting the following error in KIAM server 
```
{"level":"info","msg":"found role","pod.iam.role":"","pod.ip":"PRIVATE_IP","time":"2020-03-26T18:56:53Z"}
```
and in the agent 
```
{"addr":"PRIVATE_IP:59610","level":"error","method":"GET","msg":"error processing request: empty role","path":"/latest/meta-data/iam/security-credentials/","status":404,"time":"2020-03-26T18:46:09Z"}
{"addr":"PRIVATE_IP:59610","duration":1,"headers":{"Content-Type":["text/plain; charset=utf-8"],"X-Content-Type-Options":["nosniff"]},"level":"info","method":"GET","msg":"processed request","path":"/latest/meta-data/iam/security-credentials/","status":404,"time":"2020-03-26T18:46:09Z"}
```
I am not sure why i have this behavior. the only annotation set is the one in the namespace level
```
iam.amazonaws.com/permitted:  arn:aws:iam::ACCOUNT_D:role/PATH/*
```
but no annotations set on the deployment of the pod producing the error message above. any idea how to fix this ?

**Comment by Joseph-Irving** [comment]
That error indicates that your Pod is attempting to request credentials but you have not set that annotation on the Pod for the role. So to fix this you should set the `iam.amazonaws.com/role: ` for your pod

**Comment by mo-saeed** [comment]
@Joseph-Irving  Thanks for your answer.

The question why it's trying to request credentials? I assume if I don't specify any annotation then it shouldn't ask for any creds?

**Comment by Joseph-Irving** [comment]
That's down to your application, most things that use AWS sdks will attempt to retrieve credentials using the credentials provider chain and therefore be intercepted by Kiam.

**Comment by mo-saeed** [comment]
Ah got it. Thanks a lot for your clarification!
