### ISSUE TITLE
Handle absolute ARNs in the role annotation

### ISSUE THREAD

**Issue by ankon** [uswitch/kiam#4]
Currently kiam assumes that the IAM annotation would be something that can be literally appended to the given "base ARN". At the same time it also assumes that the value of the role annotation should be exposed on the http interface.

Using a full ARN as role breaks things: one can set the base ARN to '' without an issue, but that means the http interface now returns weird values (and from what I can see it breaks things down the road when the values contain "illegal characters" such as ':' and '/'.)

One would want absolute ARNs in some (esoteric) cross-account situations; in our case we also keep these role definitions in a separate file that should have them fully qualified for auditing purposes.

**Comment by pingles** [comment]
Sounds good. We don't use cross-account so hadn't needed it but it'd be good to add.

**Comment by ankon** [comment]
My idea here would be to check whether the role starts with `arn:`, and if so avoid the concatenation and derive the name for the HTTP "somehow" -- need to check what AWS exactly does there.

**Comment by pingles** [comment]
Going to leave a comment here to remind myself that it would be good to look at this in the future. Given the 2.0 changes this would mean moving the full role arn stuff from the server to agent process but (assuming its doable in general) shouldnt be much harder.

**Comment by allandegnan** [comment]
@pingles @ankon 

As per your comment the following seems to be working for us:-

https://github.com/pmaheshs/kiam/commit/08c3551fb85caa91574c8e5e8af16fac6bd94c9d

If you guys are happy then @pmaheshs will submit a PR. :)

**Comment by pingles** [comment]
Thanks for the submission @allandegnan- I've merged the other PR so will close this. It's in `quay.io/uswitch/kiam:v2.3`.
