### ISSUE TITLE
Race condition in assuming role of same name in 2 different accounts

### ISSUE THREAD

**Issue by mikhailadvani** [uswitch/kiam#400]
We are trying to deploy infrastructure to different AWS accounts through CI in a 3rd account and using IAM roles for authentication. Due to naming conventions, the name of the role in both the accounts is the same. This causes the second job to fail when both are triggered simultaneously. We are using complete ARNs of the role. Running the jobs one at a time causes no issues. Running different jobs at the same time cause no issues. 
KIAM version: 3.4

**Comment by pingles** [comment]
I suspect this is an issue with the way that we generated cache keys.

This has actually been overhauled as part of the work on v4 (it was extended in #430 to support session and external IDs) so should be fixed when we get v4 out.

I'm going to close this for now as it should be resolved. Thank you for reporting though!
