### ISSUE TITLE
3.6 release

### ISSUE THREAD

**Issue by stefansedich** [uswitch/kiam#403]
Just curios when we can expect a 3.6 GA release? I am unsure of the release cadence with this project and what to expect.

Additionally is anyone running 3.6-rc1 in production with success? happy to roll it out as long as there are there are no hidden surprises, I have rolled it out to development to see how it works but be good to hear any war stories.

**Comment by leosunmo** [comment]
I really need a new release as well with https://github.com/uswitch/kiam/pull/366 merged (this caused production issues for us recently) as well as https://github.com/uswitch/kiam/pull/364 (to prevent anything like that in the future). 
https://github.com/uswitch/kiam/pull/381 is also a big bonus. This is something that needs to be pushed to a stable release ASAP.

**Comment by SinFulNard** [comment]
Seems a tag was cut; https://github.com/uswitch/kiam/releases/tag/v3.6

**Comment by leosunmo** [comment]
Sweet! Just threw together a PR for the helm chart.
https://github.com/uswitch/kiam/pull/417

**Comment by leosunmo** [comment]
Hem chart has been merged, should be fine to close this now.

**Comment by leosunmo** [comment]
@stefansedich or @rhysemmas You can close this now! Should try and keep the issue count down :)

**Comment by stefansedich** [comment]
> @stefansedich or @rhysemmas You can close this now! Should try and keep the issue count down :)

oops my bad forgot to close this when we upgraded! thanks for the release.
