### ISSUE TITLE
Is it possible to exclude the redirect via kiam for specific namespaces?

### ISSUE THREAD

**Issue by Tolsto** [uswitch/kiam#412]
We currently block access to the metadata API for all namespaces but kube-system which has unrestricted and direct access to the API.
Would it be possible to enable kiam for all namespaces but kube-system, i.e. keep the direct API access for that namespace?

**Comment by frezbo** [comment]
I would also like to have the support for enabling/disabling KIAM for specific namespaces. I would really love to not use `hostNetwork`

**Comment by pingles** [comment]
In it's current implementation it's not possible; all requests from a node with an agent running will be intercepted. Your alternative is to control node placement such that only specific nodes run kube-system pods and have those nodes not load the agent proxy. 

I appreciate the request (default roles was our first issue #1) but I prefer the stance that we require all pods to have explicit roles attached. 

If I've misunderstood the rationale please do re-open but for now I'm going to say this is unlikely to change and if you wanted to you could achieve it currently through the way you configure and place kube-system pods.

Thanks!
