### ISSUE TITLE
Openshift 4.5 Agents Cannot Connect To Server

### ISSUE THREAD

**Issue by jkassis** [uswitch/kiam#416]
KIAM Server requires access to the AWS API. The IP address for that API is 169.254.169.254
![image](https://user-images.githubusercontent.com/3630156/89609681-6e11a700-d82d-11ea-8caa-c5cfbdc7d817.png)

Openshift documents clearly state that the CIDR block that contains the API endpoint is not available to containers...
https://docs.okd.io/latest/networking/understanding-networking.html

The solution is to expose the host network to the server using `hostNetwork: True`. This means that HostIPs are exposed through the "headless" service.

```
"Normal" (not headless) Services are assigned a DNS A or AAAA record, depending on the IP family of the service, for a name of the form my-svc.my-namespace.svc.cluster-domain.example. This resolves to the cluster IP of the Service.

"Headless" (without a cluster IP) Services are also assigned a DNS A or AAAA record, depending on the IP family of the service, for a name of the form my-svc.my-namespace.svc.cluster-domain.example. Unlike normal Services, this resolves to the set of IPs of the pods selected by the Service. Clients are expected to consume the set or else use standard round-robin selection from the set.

SRV records
```

KIAM requires a "headless" service for the GRPC client in the agent which does load-balancing using the individual entries of the DNS recorde (https://kubernetes.io/blog/2018/11/07/grpc-load-balancing-on-kubernetes-without-tears/)

But here's the problem... Openshift does not provide pod-level networking routes to cluster node IPs.

So, the server starts, the agents attempt to connect and they timeout during connection.

**Comment by jkassis** [comment]
Host IPs are exposed through the service because KIAM deploys a headless service for GRPC.

**Comment by jkassis** [comment]
as i look into this further... openshift does not even enable pod to host networking when both pods are running on their respective host networks.

**Comment by jkassis** [comment]
unfortunately after quite a lot of research, i have to replace kiam with kube2iam. the client-server architecture of kiam just doesn't work with openshift 4 which has hardcoded iptables rules that restrict access to the AWS API to the host network. this forces the server to run in the host network, which means that agents running on other nodes will be unable to connect as there is no out of the box routing for pods identified by hostIP. this is true for all services, including headless services.

**Comment by jkassis** [comment]
https://github.com/jtblin/kube2iam

**Comment by jkassis** [comment]
kube2iam suffers similar problems with default OpenShift CNI plugins. I eventually changed to calico and things are working well with kube2iam and would probably work well with kiam as well.

**Comment by pingles** [comment]
Thanks for reporting. I'm going to close this issue but people can still find it if they need to.
