### ISSUE TITLE
Kiam doesn't work with the latest aws-go-sdk

### ISSUE THREAD

**Issue by elafarge** [uswitch/kiam#43]
First of all, thanks a lot for the great work on `kiam`. Providing the ability to grant IAM roles to pods i/o nodes is a big security improvement wrt. deploying Kubernetes clusters atop AWS :)

I came accross an issue with the Golang AWS SDK today though: somehow, my Golang pods were trying to assume the role given to their underlying EC2 instance instead of using the one I was providing in the annotation.

I think I found the cause of the issue: the AWS SDK in Go calls the `/iam/security-credentials/` endpoint without the trailing slash and, therefore, kiam doesn't intercept the request and passes it to the "real" instance metadata API endpoint (https://github.com/aws/aws-sdk-go/blob/db3e1e27b1ace4fc57be9c5cf7cea0566bd12034/aws/credentials/ec2rolecreds/ec2_role_provider.go#L128).

I made a PR to make the trailing slash optional in `gorilla/mux` route configuration, it seems to fix the issue: https://github.com/uswitch/kiam/pull/42 .

**Comment by elafarge** [comment]
So as a matter of fact, this only occurs on generation 5 AWS instances (`m5`, `c5`, ...). See the discussion [here](https://github.com/uswitch/kiam/pull/42) for details.

This is now fixed and the fix has been merged in `master`, I'm closing the issue :)

**Comment by hjacobs** [comment]
For reference, `kube2iam` had the same issue: https://github.com/jtblin/kube2iam/pull/130
