### ISSUE TITLE
Allow MaxConnectionAge on Server

### ISSUE THREAD

**Issue by pingles** [uswitch/kiam#433]
gRPC issues highlighted in https://github.com/uswitch/kiam/issues/425 mention a preference to controlling flow of updates of the connection addresses via `MAX_CONNECTION_AGE`.

This should be added as a flag to the server, and passed when creating the gRPC server:

```
grpc.NewServer(grpc.KeepaliveParams(keepalive.ServerParameters{MaxConnectionAge: maxConnAge}))
```

The default value is infinity (https://github.com/grpc/grpc-go/blob/master/keepalive/keepalive.go#L60) but could be overridden to force clients to re-resolve and reconnect more regularly.

Should help #425 along with updating the gRPC Go version.

**Comment by stefansedich** [comment]
@pingles do we want to keep the existing default of `infinity` or should we default to something more sensible that suits our needs better?
