### ISSUE TITLE
Events missing on pods due to use of deprecated metadata.selfLink

### ISSUE THREAD

**Issue by AlexLast** [uswitch/kiam#484]
Since upgrading to Kubernetes `1.20` we no longer get `kiam` related events on pods due to the use of the deprecated `metadata.selfLink` field. This was deprecated in Kubernetes `1.16` and [removed](https://github.com/kubernetes/kubernetes/pull/94397) in `1.20`

We see error logs relating to this in `kiam-server`, example:

```
ERROR: logging before flag.Parse: E0706 15:08:28.333117       1 event.go:260] Could not construct reference to: '&v1.Pod{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, 
<redacted>
 due to: 'selfLink was empty, can't make reference'. Will not report event: 'Warning' 'KiamCredentialError' 'failed retrieving credentials: AccessDenied: User: arn:aws:sts::<redacted>:assumed-role/<redacted>/<redacted> is not authorized to perform: sts:AssumeRole on resource: arn:aws:iam::<redacted>:role/<redacted>'
```

Looks like it's using `EventRecorder` from `client-go` although `v7.0.0` looks pretty old, I'm guessing the client libraries will need updating to use a version that constructs the object reference using different fields.

**Comment by pjaak** [comment]
I am also getting the same issues sadly and its effecting my pods ability to access AWS resources:

<img width="1671" alt="Screen Shot 2021-08-05 at 8 52 33 am" src="https://user-images.githubusercontent.com/45154743/128268791-4ce6e74e-63fd-4ee2-8542-8b6e88d53c48.png">
<img width="1672" alt="Screen Shot 2021-08-05 at 9 35 39 am" src="https://user-images.githubusercontent.com/45154743/128268849-0f407520-c0d2-459c-a499-5e47a50f6986.png">

I am not sure what to do tbh.

**Comment by jjo** [comment]
also facing this (v1.20), with [other projects also facing this](https://github.com/kubernetes/kubernetes/search?q=%22selfLink+was+empty%2C+can%27t+make+reference%22&type=issues), with fixes like these https://github.com/kubernetes-csi/external-provisioner/pull/323
