### ISSUE TITLE
Unable to fetch credentials using kube-bridge host interface

### ISSUE THREAD

**Issue by gappan** [uswitch/kiam#52]
We are running [kube-router](https://www.kube-router.io/) for the k8s networking. We moved away from Calico. 

We changed the host-interface to `kube-bridge`. (Ref: https://github.com/jtblin/kube2iam/issues/120). 

Logs of kiam-agent : 
```
{"addr":"10.2.10.2:45980","level":"error","method":"GET","msg":"error processing request: rpc error: code = Unavailable desc = there is no address available","path":"/latest/meta-data/iam/security-credentials/","status":500,"time":"2018-04-19T13:59:14Z"}
{"addr":"10.2.10.2:45980","headers":{"Content-Type":["text/plain; charset=utf-8"],"X-Content-Type-Options":["nosniff"]},"level":"info","method":"GET","msg":"processed request","path":"/latest/meta-data/iam/security-credentials/","status":500,"time":"2018-04-19T13:59:14Z"}
```

`kiam-master` was retrieving the credentials successfully.  The `kiam-master` and `kiam-server` are running in different subnets. 

Please let me know if you need any other information.

**Comment by pingles** [comment]
Hmmm, that looks like it's getting an error communicating with the kiam server. 

```
rpc error: code = Unavailable desc = there is no address available
```

Is reported from the gRPC client within the agent trying to communicate with the server. There have been other gRPC communication issues with TLS that were difficult to debug without more data.

Could you please use the suggestions in https://github.com/uswitch/kiam/issues/17#issuecomment-353358906 to get more gRPC trace data from the agent to see why it's unable to communicate with the server.

Thanks!

**Comment by gappan** [comment]
@pingles Thanks for the link :), it did help me to debug the issue. It was due to the `service` endpoint of the `kiam-server` which we fixed and it works ! Closing the issue.
