### ISSUE TITLE
Support all "API versions" for the IAM parts

### ISSUE THREAD

**Issue by ankon** [uswitch/kiam#6]
Currently kiam only reacts to the 'latest' API version, but there are more. It seems reasonable to be able to whitelist API versions that work, and to report errors for all kiam-handled paths on not-supported API versions (to prevent leaking of credentials of the node itself).

**Comment by pingles** [comment]
I'm going to close this for now- all non-credentials APIs are proxied straight through to the metadata api, and although the version is captured we don't differentiate between versions (although maybe we should at some point).
