### ISSUE TITLE
Reduce 200 ping requests in logs

### ISSUE THREAD

**Issue by c-knowles** [uswitch/kiam#70]
Do we need the logs with contents `processed request` for `path: /ping` and `status: 200` at info level? I've been trying to investigate a problem but the logs are kind of swamped with these. Kubernetes will already be monitoring the response although there's some value in logging the reason why it's failing on non 200s because by that point it might be impossible to get into the container to investigate.

My proposal is we filter out the 200s for the ping endpoint or switch them to debug.

**Comment by pingles** [comment]
+1

Happy to take a PR for that (I think switching to debug is probably the option I'd prefer).
