### ISSUE TITLE
High resource utilization when not using limits 

### ISSUE THREAD

**Issue by camilb** [uswitch/kiam#72]
Have `kiam` deployed on 3 clusters in AWS and didn't use resource limits. After few days I started noticing that the amount of resource utilization is constantly increasing. Deleting the pods fixed the resource consumption for a few hours but then starts again and is only increasing in time, never goes back. 

On 2 clusters didn't use any role yet, just deployed `kiam` so no requests are made and the logs don't show anything weird. 
Now I'm setting limits and see how it goes, but don't understand why it needs this amount of CPU

Here are two screenshots using `kubectl top pods` and `top` inside the container
<img width="1680" alt="screen shot 2018-05-25 at 11 25 23" src="https://user-images.githubusercontent.com/2655869/40547912-7c41f6c8-6033-11e8-8363-c4b553e2558b.png">
<img width="949" alt="screen shot 2018-05-25 at 11 24 20" src="https://user-images.githubusercontent.com/2655869/40547914-7c61f6b2-6033-11e8-9552-1d295c2628b1.png">

**Comment by camilb** [comment]
Doesn't seems to be a problem anymore after setting pod limits.

<img width="983" alt="screen shot 2018-05-28 at 13 55 01" src="https://user-images.githubusercontent.com/2655869/40617359-6119c63e-628e-11e8-9116-24f7b04af8da.png">

**Comment by osterman** [comment]
My guess is it's still a problem, but mitigated by automatic restarts. Do you see your pods getting restarted?

**Comment by camilb** [comment]
>My guess is it's still a problem, but mitigated by automatic restarts. Do you see your pods getting restarted?

It was more of a CPU issue, so no restarts in this case but they get `OOMKilled` sometimes (some agents once and server 3 times in the last 17 days). This are the limits I currently use and I guess increasing a little bit the memory limit, will eliminate the restarts completly:
```yaml
         resources:
           limits:
             cpu: 50m
             memory: 100Mi
           requests:
             cpu: 5m
             memory: 50Mi
```

**Comment by sbuliarca** [comment]
If this is still of interest to anybody: even with limits, we got really high [CPU load](http://blog.scoutapp.com/articles/2009/07/31/understanding-load-averages) with versions < 3.0. See in [this comment](https://github.com/uswitch/kiam/issues/147#issuecomment-432634676) how we managed to work around it with `v2.8`
