### ISSUE TITLE
Leading / from IAM path has to be omitted in annotations

### ISSUE THREAD

**Issue by 2rs2ts** [uswitch/kiam#75]
Good: `k8s-roles/myserver`
Bad: `/k8s-roles/myserver`

My company uses the IAM path to restrict which roles the nodes running kiam-server can assume. One of the most common mistakes developers (including myself!) make is forgetting that you must omit the leading `/` from the path in the annotations.

I think this should either be documented or merely accepted either way. I'm happy to implement whatever acceptance criteria you come up with, when I have the time to. I would have just submitted a PR but I wanted feedback and AC first.

**Comment by roffe** [comment]
Imho we should accept leading slash and just strip it, I made a PR that's running in my staging cluster without issues so far.

Image is at `roffe/kiam:issue-75-1` for anyone that wants to give it a spin

**Comment by pingles** [comment]
Interesting.

I guess if `/` is reserved in role names then it'd be safe to have Kiam detect and remove the prefix if it exists. Full ARN names can also be used to be explicit.

1. `k8s-roles/myserver` would expand to `arn:aws:iam::account-id:role/k8s-roles/myserver`
2. `/k8s-roles/myserver` should expand to `arn:aws:iam::account-id:role/k8s-roles/myserver`
3. `arn:aws:iam::account-id:role/k8s-roles/myserver` would expand to itself.

Is that correct? Is there ever a time where 2 should _not_ remove the prefix?

**Comment by roffe** [comment]
Afaik there is no situation where the leading slash should not be removed

The problem i think is that DefaultResolver would return a full base ARN ending in a / and when we append a role starting with / we would end up with something like:

`/k8s-roles/myserver expand to arn:aws:iam::account-id:role//k8s-roles/myserver`

and here the aws api would complain about the ARN containing double slashes
