### ISSUE TITLE
Require node iam permissions

### ISSUE THREAD

**Issue by chrislovecnm** [uswitch/kiam#8]
What perms does the node require for kiam to function?

**Comment by pingles** [comment]
Thanks for bringing it up- had been meaning to document :)

I've add some notes to the doc on what you need as you have to configure roles for the nodes as well as policy for each role you want to allow the cluster to assume.

On our list of things to potentially do is extend kiam with a CRD for creating roles which could shield cluster users from needing to know about node roles etc.

Let me know if you think the doc notes are sufficient and I'll close this.

**Comment by chrislovecnm** [comment]
I am really interested in having a solution that lives on the masters only,  not certain how to do that, but assume role is pretty nasty perm if the nodes get rooted.

**Comment by chrislovecnm** [comment]
Ping me on in the PR if you like, or let me know when it is merged

**Comment by pingles** [comment]
We talked a little about an alternate implementation in #7: separate kiam into two components, one which runs in the daemonset as an agent and the server piece which could then run as a deployment but pinned to be particular nodes via a selector (so you could designate only a handful of nodes as ones that would talk to the AWS API).

It doesn't ensure stuff only runs on masters but would at least ensure a smaller subset have permissions?

If that sounds good I'll see if I/we can get some time to work on it over the next few weeks (I'm away on holiday for a week so won't be doing much).

**Comment by pingles** [comment]
@chrislovecnm its been a while but just so you know I've started working on this- hopefully should have it merged in the next day or so.

**Comment by pingles** [comment]
@chrislovecnm I've merged the changes we've made into master and Docker images are available on quay.io. We're running it on one of our clusters currently to see how it goes before testing on our larger cluster next week.

The image we're currently running is `quay.io/uswitch/kiam:v2.0-rc1`. Deployment artifacts are in `./deploy` and there's some notes around deployment in `./docs`: this change adds gRPC between the server and agent processes which requires some generated TLS assets to secure.

Hopefully this makes it easier to deploy kiam in the topology you were hoping for?

**Comment by chrislovecnm** [comment]
@pingles you guys should swing by sig-aws and demo :)  Let me task a peek.

**Comment by chrislovecnm** [comment]
```json
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": [
        "sts:AssumeRole"
      ],
      "Resource": "*"
    }
  ]
}
```

Is this just required on the master now?  Also, can you run AssumeRole with less privs?  For instance you only need to give pods s3 perms, can you run with just AssumeRole for that?

**Comment by pingles** [comment]
Hi @chrislovecnm sorry- hadn't seen your messages here!

Yep- v happy to demo some time. Keep meaning to come by the sigs and office hours meetups more :) I've just tagged `v2.0` as we've been running this (and some rcs) for a few days and things seem to work well for us.

About the policy- that's the correct. Only the nodes running the server process will call AWS and need access to `sts:AssumeRole`.

I'm not sure if you can specify `Resource` to limit the `sts:AssumeRole` call to just a subset of roles, or whether its controlled just through the trust permissions of the role. Currently we will let users configure an IAM role- this then must have the right [trust relationship](https://github.com/uswitch/kiam/blob/master/docs/IAM.md#application-roles) added to allow the node to call `sts:AssumeRole` for that role. So you can control what stuff can be assumed, but you have to do it from the assumed role side (rather than the instance policy)?

**Comment by emmanuel** [comment]
Regarding this point:
>I'm not sure if you can specify Resource to limit the sts:AssumeRole call to just a subset of roles, or whether its controlled just through the trust permissions of the role. Currently we will let users configure an IAM role- this then must have the right trust relationship added to allow the node to call sts:AssumeRole for that role. So you can control what stuff can be assumed, but you have to do it from the assumed role side (rather than the instance policy)?

As you probably know, you can both constrain the roles that can be assumed via the IAM policy of the assuming role (in the `Resources` arg of the role which grants the `sts:AssumeRole` action, which can be a list, and which permits glob patterns), *and* every role that can be assumed must reciprocally "allow itself to be assumed" via the trust relationship.

**Comment by pingles** [comment]
@emmanuel thanks, good to know. i wasn't aware- currently we control exclusively via the role that is attempting to be assumed but good to know you can specify via this also. 

I'm going to leave this issue open for now until I can get a chance to write-up a better IAM background and replace in Docs (unless anyone else beats me :-). Once I've done that I'll probably mark this issue closed. #28 was added recently too which also helps to structure IAM so be good to fold those into the same doc.

Thanks for everyone's thoughts so far!

**Comment by pingles** [comment]
Given #139 I'm going to close this issue for now.
