### ISSUE TITLE
Periodically getting `The security token included in the request is expired` from pod/app

### ISSUE THREAD

**Issue by kiich** [uswitch/kiam#90]
Using kiam in our cluster and most of the time, working brilliantly.
However, every so often, no pattern that I can see, we see error from our pod/app, something like:
```
stack_trace:	 java.util.concurrent.ExecutionException: com.amazonaws.services.dynamodbv2.model.AmazonDynamoDBException: The security token included in the request is expired (Service: AmazonDynamoDBv2; Status Code: 400; Error Code: ExpiredTokenException; Request ID: ...)
```

The app recovers and carries on working but I am having a hard time trying to pin point what is going in from kiam's point of view as by the time it happens, the logs have rotated already (which I am working on as well so i can have some thing to diagnose later).

I was looking at the `--session-duration` flag on server and was wondering how that works and if that could be something I can tune?

theory is that during kiam sts duration expires/expiring, our app just happens to make a request which then gets this error. Any other time, the request from the app works via kiam perfectly fine.

**Comment by pingles** [comment]
@kiich that error sounds like it's using credentials that should have expired already. The `--session-duration` flag configures how long sessions are valid for from STS. If you set that to be `30m`, for example, session credentials would be valid for 30 minutes. Depending on the release of Kiam it should try to update credentials 5 minutes or so before the end of that expiry.

It may be worth setting the session duration to be slightly longer. It would also be helpful to see any error messages from Kiam's server process to see if there's something to explain why it's been unable to refresh the credentials.

**Comment by kiich** [comment]
@pingles Thanks for the clarification - I'll give it a go in increasing the `session-duration` flag.
I see the TTL feature for updating credentials is in v2.8 - we are on v2.7 so that's good to know we can upgrade although I was under the impression to hold back for that version to use in `kube-aws` which is what we are using to spin up our clusters?

Anyways, I'll go ahead with the duration increase as well as trying to get hold Kiam server logs. I'm having trouble getting those because by the time I find the error in our app's log, the Kiam server logs have been rotated already and long gone. Is there a config option for those as well so i can keep more rotated logs?

**Comment by pingles** [comment]
@kiich log retention will be determined by how your cluster nodes are configured (i'm not familiar with how that's done in kube-aws). We use fluentd to ship logs away from our cluster nodes and into ElasticSearch, I'd recommend doing something similar so it's easier to aggregate and access

**Comment by kiich** [comment]
thanks @pingles

**Comment by kiich** [comment]
We think increasing the `session-duration` flag value has made a difference - so closing this!
Thanks for your help @pingles !
